export enum BaseErrorCode {
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
    NOT_FOUND = 'NOT_FOUND',
    FORBIDDEN = 'FORBIDDEN',
    UNKNOWN_ERROR = 'UNKNOWN_ERROR',

    READ_CSV_FILE_ERROR = 'READ_CSV_FILE_ERROR',
}